[package]
name = "equity_consensus"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
equity_types = { path = "../equity_types" }

sha2 = "0.10"
tokio = { version = "1.19", features = ["full"] }
ed25519-consensus = "2"