[package]
name = "testcrate"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "common"
path = "src/lib/common.rs"

[dependencies]
equity-client = { path = "../equity-client" }
equity-types = { path = "../equity-types" }

tokio = { version = "1.19", features = ["full"] }
