[package]
name = "testcrate"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "common"
path = "src/lib/common.rs"

[dependencies]
equity_client = { path = "../equity_client" }
equity_types = { path = "../equity_types" }

tokio = { version = "1.19", features = ["full"] }
