[package]
name = "equity_p2p"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.19", features = ["full"] }
tungstenite = "0.17"
ed25519-consensus = "2"
serde_json = "1.0"

