[package]
name = "equity-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
futures = "0.3"
surf = { version = "2.2", default-features = false, features = ["h1-client-rustls"] }
equity-types = { path = "../equity-types" }
tracing = "0.1"
tracing-subscriber = "0.3"