[package]
name = "equity_core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
equity_storage = { path = "../equity_storage" }
equity_types = { path = "../equity_types" }

async-trait = "0.1"
axum = "0.5"
borsh = "0.9"
hyper = "0.14"
mime = "0.3"
thiserror = "1.0"
tokio = { version = "1.19", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
